spring:
  datasource:
    url: jdbc:mysql://db.mysql:3366/content_center
    hikari:
      username: root
      password: Jc1207
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos.han:8848
        service: content-center
        #namespace: 198b9493-90f1-435e-8b10-3113a628acaa   指定namespace
        cluster-name: BJ  #指定集群名称
  application:
    name: content-center
logging:
  level:
    com:
     itmuch:
      contentcenter: info
server:
  port: 8081
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
